config/routes.rb
MommySocialApp::Application.routes.draw do
  resources :profiles

  resources :moms

end

app/models/mom.rb
class Mom < ActiveRecord::Base
  
  has_many :profiles
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  belongs_to :mom
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/moms_controller.rb
class MomsController < ApplicationController
  # GET /moms
  # GET /moms.json
  def index
    @moms = Mom.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @moms }
    end
  end

  # GET /moms/1
  # GET /moms/1.json
  def show
    @mom = Mom.find(params[:id])
    @profiles = Mom.find_by_id(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mom }
    end
  end

  # GET /moms/new
  # GET /moms/new.json
  def new
    @mom = Mom.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mom }
    end
  end

  # GET /moms/1/edit
  def edit
    @mom = Mom.find(params[:id])
  end

  # POST /moms
  # POST /moms.json
  def create
    @mom = Mom.new(params[:mom])

    respond_to do |format|
      if @mom.save
        format.html { redirect_to @mom, notice: 'Mom was successfully created.' }
        format.json { render json: @mom, status: :created, location: @mom }
      else
        format.html { render action: "new" }
        format.json { render json: @mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /moms/1
  # PUT /moms/1.json
  def update
    @mom = Mom.find(params[:id])

    respond_to do |format|
      if @mom.update_attributes(params[:mom])
        format.html { redirect_to @mom, notice: 'Mom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moms/1
  # DELETE /moms/1.json
  def destroy
    @mom = Mom.find(params[:id])
    @mom.destroy

    respond_to do |format|
      format.html { redirect_to moms_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moms_helper.rb
module MomsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MommySocialApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/moms/_form.html.erb
<%= form_for(@mom) do |f| %>
  <% if @mom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mom.errors.count, "error") %> prohibited this mom from being saved:</h2>

      <ul>
      <% @mom.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moms/edit.html.erb
<h1>Editing mom</h1>

<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: blue;
      font-family: 'Tangerine', serif;
      font-size: 25px;
    }
  </style>
</head>

<%= render 'form' %>

<%= link_to 'Show', @mom %> |
<%= link_to 'Back', moms_path %>

app/views/moms/index.html.erb
<!DOCTYPE html Public>
<div class="companybox">
<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: #B22222;
      font-family: 'Tangerine', serif;
      font-size: 25px;
    }
  </style>
</head>
<h1>The Mommy Network</h1>
<h2>Social Networking for Moms on the Go!</h2>


<h3>Our Mommies!</h3>

<table>
  <tr>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moms.each do |mom| %>
  <tr>
    <td><%= mom.user %></td>
    <td><%= link_to 'Mommy Profile', mom %></td>
    <td><%= link_to 'Edit Profile', edit_mom_path(mom) %></td>
    <td><%= link_to 'Delete Profile', mom, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Sign Up Today!', new_mom_path %>

<br />

<br />

<a href="mailto:tim@mommynetwork.com" class="button">					
						Send Us an Email!
					</a>
</div>

app/views/moms/new.html.erb
<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: blue;
      font-family: 'Tangerine', serif;
      font-size: 25px;
    }
  </style>
</head>


<h1>Add your profile and start searching today!</h1>

<%= render 'form' %>

<%= link_to 'Back', moms_path %>

app/views/moms/show.html.erb
<!DOCTYPE html Profile>

<div class="companybox">
<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: #B22222;
      font-family: 'Tangerine', serif;
      font-size: 48px;
    }
  </style>
</head>

<p id="notice"><%= notice %></p>

<p>
  <b>Mommy:</b>
  <%= @mom.user %>

  <% @mom.profiles.each do |profile| %>

    <li> Age - <%= profile.age%></li>
    <li> Neighborhood - <%= profile.neighborhood %></li>
    <li> Hobbies - <%= profile.hobby %></li>
    <li> Kids - <%= profile.children %></li>

    <% end %>

<b>
    <a href="mailto:<%= @mom.user %>" class="button">					
    						Send <%= @mom.user%> an Email!
    					</a>

</p>


<%= link_to 'Edit Mom', edit_mom_path(@mom) %> |
<%= link_to 'Back', moms_path %> |
<%= link_to 'Edit Profile', edit_profile_path(@profile) %>

</div>

app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :neighborhood %><br />
    <%= f.text_field :neighborhood %>
  </div>
  <div class="field">
    <%= f.label :hobby %><br />
    <%= f.text_field :hobby %>
  </div>
  <div class="field">
    <%= f.label :children %><br />
    <%= f.text_field :children %>
  </div>
  <div class="field">
    <%= f.label :mom_id %><br />
    <%= f.collection_select :mom_id, Mom.all, :id, :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: blue;
      font-family: 'Tangerine', serif;
      font-size: 25px;
    }
  </style>
</head>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>
<%= link_to 'Home', moms_path %>

app/views/profiles/index.html.erb
<!DOCTYPE html Public>

<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: #B22222;
      font-family: 'Tangerine', serif;
      font-size: 48px;
    }
  </style>


<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Age</th>
    <th>Neighborhood</th>
    <th>Hobby</th>
    <th>Children</th>
    <th>Mom</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.age %></td>
    <td><%= profile.neighborhood %></td>
    <td><%= profile.hobby %></td>
    <td><%= profile.children %></td>
    <td><%= profile.mom_id %></td>
    <td><%= link_to 'Mommy Profile', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profile', new_profile_path %>
<%= link_to 'Home', moms_path %>

app/views/profiles/new.html.erb
<!DOCTYPE html Public>
<div class="companybox">
<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: #B22222;
      font-family: 'Tangerine', serif;
      font-size: 48px;
    }
  </style>

<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="companybox">

<head>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
  <style>
    body {
      color: #B22222;
      font-family: 'Tangerine', serif;
      font-size: 48px;
    }
  </style>
</head>

<p id="notice"><%= notice %></p>

<p>
  <b>Age:</b>
  <%= @profile.age %>
</p>

<p>
  <b>Neighborhood:</b>
  <%= @profile.neighborhood %>
</p>

<p>
  <b>Hobby:</b>
  <%= @profile.hobby %>
</p>

<p>
  <b>Children:</b>
  <%= @profile.children %>
</p>



<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

</div>